=== theosenoussaoui/website/old/scripts/schema/keebs-data-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "owner",
    "name",
    "pcb",
    "switches",
    "keyset",
    "description",
    "photos"
  ],
  "properties": {
    "owner": {
      "$id": "#/properties/owner",
      "type": "string",
      "title": "The Owner Schema",
      "minLength": 1,
      "examples": [
        "Zekth"
      ],
      "pattern": "^(.*)$"
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The Name Schema",
      "minLength": 1,
      "examples": [
        "der 60%"
      ],
      "pattern": "^(.*)$"
    },
    "pcb": {
      "$id": "#/properties/pcb",
      "type": "string",
      "title": "The Pcb Schema",
      "minLength": 1,
      "examples": [
        "KP XD64"
      ],
      "pattern": "^(.*)$"
    },
    "switches": {
      "$id": "#/properties/switches",
      "type": "string",
      "title": "The Switches Schema",
      "minLength": 1,
      "examples": [
        "Kailh Box Brown"
      ],
      "pattern": "^(.*)$"
    },
    "keyset": {
      "$id": "#/properties/keyset",
      "type": "string",
      "title": "The Keyset Schema",
      "minLength": 1,
      "examples": [
        "GMK Plum"
      ],
      "pattern": "^(.*)$"
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "The Description Schema",
      "minLength": 1,
      "examples": [
        "c'est un clavier avec des touches"
      ],
      "pattern": "^(.*)$"
    },
    "photos": {
      "$id": "#/properties/photos",
      "type": "array",
      "title": "The Photos Schema",
      "items": {
        "$id": "#/properties/photos/items",
        "type": "string",
      "minLength": 1,
      "title": "The photo filename Schema",
        "examples": [
          "zekth-60-1.jpg"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== theosenoussaoui/website/old/src/data/keyboards.json
[
  {
    "owner": "Zekth",
    "name": "der 60%",
    "pcb": "KP XD64",
    "switches": "Kailh Box Brown",
    "keyset": "GMK Plum",
    "description": "c'est un gros clavier de merde",
    "photos": ["zekth-60-1.jpg"]
  },
  {
    "owner": "Zekth",
    "name": "Stealth Split",
    "pcb": "Keeb.io Quefrency 60%",
    "switches": "Kailh Box Black",
    "keyset": "Gentleman Black PBT",
    "description": "Clavier split tout pété",
    "photos": ["zekth-quefrency-1.jpg"]
  }
]
